### ISSUE TITLE
The plugin seems broken on both FF and Chrome

### ISSUE THREAD

**Issue by mihirkumar** [elliotwaite/thumbnail-rating-bar-for-youtube#17]
The blue bar underneath the thumbnails is missing.

**Comment by elliotwaite** [comment]
Thanks for reporting this. The extension just started going over its YouTube Data API quota of 1,000,001 requests per day, probably from an increase in users, so the requests at the end of the day may have been failing. I just released a fix (version 0.0.42) that should resolve this issue.

Let me know if the update does not resolve the issue for you.

**Comment by scharmach** [comment]
At least for me, the issue hasn't been resolved with the fix in version 0.0.42. The bar is still missing, unfortunately.

**Comment by jasonTong68** [comment]
The bar is temporarily fixed when the addon is disabled then re-enabled again. However, the bar disappears again after a period of time.

**Comment by elliotwaite** [comment]
Just released version 0.0.44. It fixes a compatibility issue with Firefox 70 and it also reverts the attempted quota fix applied in 0.0.42 which actually made it worse. So there will still probably be quota issues around late in the day pacific time since the daily quota gets reset every day at midnight pacific time. I am not sure how to resolve this issue until Google increases my YouTube API quota, but I just sent them another email to try to get an update on their progress. I'll leave this issue open until the quota is increased.

**Comment by ishanray** [comment]
Seems like it is still not working in chrome / brave. Tried disabling and reenabling.

**Comment by elliotwaite** [comment]
@ishanray, yeah, it's been buggy for me too. Still waiting on the quota increase. But some slight progress has been made. Google emailed me two days ago requesting a screen recording of me using the Chrome extension, which I sent them. So one step closer, but still waiting for their next reply.

**Comment by asdfzxh8** [comment]
Gooogarrr Please, can't use Youtube without this.

**Comment by asdfzxh8** [comment]
Goooooogaaaaaaaarrrrrrrrrr

**Comment by Banderi** [comment]
Any update on this? Not sure if it's the same issue, bars are still not loading in for me. Stopped working a couple days ago.

**Comment by elliotwaite** [comment]
Welp, first the bad news. Not only did they not increase the quota, but they revoked my previous quota of 1,000,001 queries per day. My current quota is now 0 queries per day, which is why the extension has completely stopped working. Here is the message they sent me:

> Hello,
> 
> We have reviewed your quota extension request for project number <project_number> and have revoked the allocated quota for your API Client(s) as it is out of compliance on the following Youtube API Services - Developer Policy:
> - [Policy F. 1 (User Experience - YouTube Look and Feel)](https://developers.google.com/youtube/terms/developer-policies#f-user-experience)
> 
> Please do not reply to this email, you may complete and submit [this form](https://support.google.com/youtube/contact/yt_api_form) to re-apply once the above concerns have been addressed.
> 
> Thanks,
> 
> YouTube API Services team

Here is what the policy they referred to says - [Policy F. 1 (User Experience - YouTube Look and Feel)](https://developers.google.com/youtube/terms/developer-policies#f-user-experience):
> 
> Innovative user experiences and user interface designs are among the most valuable contributions that API Clients can provide to the YouTube community. That said, YouTube's designers and engineers put a lot of thought into designing YouTube Applications to ensure that those Applications provide a great user experience.
> 
> Taking both of those points into account, your API Clients must not change or interfere with user interfaces in YouTube Applications unless you have obtained YouTube's prior written approval. You can request that approval at [this form](https://services.google.com/fb/forms/ytapiuimodification/).

So I guess I have to get prior consent before I can change the user interface by adding the rating bars to the bottom of the thumbnails. I may try requesting approval with that form they mentioned ([YouTube API: User Interface Modification Application](https://services.google.com/fb/forms/ytapiuimodification/)), but since my last request for the quota increase required 7 follow up emails and took almost 5 months to complete, and it backfired, I'm still deciding.

But now the good news. I came up with an idea for a workaround. I can add a text field to the extension's settings page to allow users to enter in their own YouTube Data API key. Signing up for an API key is free and you usually get a starting quota of 10,000 queries per day, which should be enough for individual users. To keep the keys private, the extension will only store the key locally on the user's computer and it won't get uploaded anywhere. I'll include instructions for how to sign up for a free key with the next release. I'll try to have it finished soon.

**Comment by Banderi** [comment]
Oof. Jesus, YouTube, you're really dropping the ball lately.
I don't mind setting up a local Data API key if it's not a headache.... but jeez, this sucks.

**Comment by Nornec** [comment]
I had a thought this would happen. This plugin actively changes the way i discover content on YouTube, so their action makes sense (though, why they don't take the same steps to thwart uBlock is beyond me). However @elliotwaite thank you so much for keeping this project running and updated. This is, by far, the most useful YouTube tool I've used -- the API key idea is a good one; I'll certainly be taking part.

**Comment by Banderi** [comment]
I don't think uBlock relies on the YouTube Data API, so that's why they're not simply "revoking access" to it. That said, I'm sure they don't officially endorse it either. On the other hand, Chrome from what I recall *did* [indeed announce they would be sort of dropping support for tech required for uBlock to function, at least partially.](https://www.ghacks.net/2019/10/12/the-end-of-ublock-origin-for-google-chrome/)

**Comment by elliotwaite** [comment]
Just released an update (version 0.1.1) that allows you to enter in a personal YouTube Data API key. Instructions for setting up a free API key have been added to the README: https://github.com/elliotwaite/thumbnail-rating-bar-for-youtube

Let me know if you run into any issues, or if you have any suggestions for how the setup instructions could be improved.

**Comment by Banderi** [comment]
I'm going through the instructions now; first problem I encountered:
This requires a credit card number.
Even if Google states clearly that it's only for security and will NOT draw money from it, I'm afraid 99% of people will never go with this. If there's no way around it, they (and probably me as well) will go looking for another extension; I'm gonna see if there's any userscript that does this in a similar way, or make one myself with scraping, even though I'm sure that'll be playing with fire.

This isn't to say I'm criticizing your approach, the bypass makes perfect sense and it's the most compliant with the terms/easiest to implement. This is just to say, expect a LOT of people complaining and uninstalling as a result; I truly hope YouTube comes to senses or another way around this comes about, but that's just flat hope.

Best of luck with this nonetheless, I'll stick around and help with feedback if I can, since I really love this extension.

**Comment by elliotwaite** [comment]
I forgot that the sign-up step asked for a credit card. But I think you're right, that step isn't actually required, phew. I removed it from the instructions. I also added a note about not clicking that first "CREATE CREDENTIALS" button that shows up. Thanks for the feedback!

**Comment by mihirkumar** [comment]
Yeah entering the Youtube API key makes the plugin work again as normal. Thanks.
